spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: transaction_user
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/transaction_db
    user: transaction_user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect