server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}
    topic: ${KAFKA_TRANSACTION_TOPIC:TRANSACTION.TOPIC}
  cache:
    cache-names: "rateRequests"
    caffeine:
      spec: "maximumSize=200,expireAfterWrite=1d"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/transaction_db
    username: transaction_user
    password: password
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/transaction_db
    user: transaction_user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true